WebApplication1/WebApplication1/Controllers/CreateController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Numerics;
using System.Security.Cryptography;

using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CreateController : Controller
    {

        public ActionResult UtworzPrzelewCykliczny(Przelewy_Cykliczne pr, string password, string kod, string check_code)
        {
            using (MD5 md5Hash = MD5.Create())
            {
                if (Session["Klient"] == null)
                {
                    TempData["title"] = "Błąd";
                    TempData["message"] = "Aby uzyskać dostęp do tej strony należy zalogować się do serwisu";
                    TempData["type"] = "error";
                    return RedirectToAction("Login", "Home");
                }
                Klient kl = (Klient)Session["Klient"];

                using (DB_Entities db = new DB_Entities())
                {
                    Kody_Autoryzujace k = db.Kody_Autoryzujace.FirstOrDefault(p => p.kod.Equals(check_code) && p.aktywny == true);
                    if (!check_code.Equals(new RegisterController().GetMd5Hash(md5Hash, kod)) || !kl.haslo.Equals(new RegisterController().GetMd5Hash(md5Hash, password)) || k == null)
                    {

                        TempData["title"] = "Błąd";
                        TempData["message"] = "Podałeś niepoprawne dane";
                        TempData["type"] = "error";

                        return RedirectToAction("PanelKlienta", "Home");
                    }
                    if (!ModelState.IsValid)
                    {
                        TempData["title"] = "Błąd";
                        TempData["message"] = "Nieoczekiwany błąd";
                        TempData["type"] = "error";
                        return RedirectToAction("PanelKlienta", "Home");
                    }

                    else
                    {
                        Konta k2 = db.Kontas.FirstOrDefault(p => p.numer_konta.Equals(pr.od_kogo));
                        Typy_Konta tk = db.Typy_Konta.FirstOrDefault(p => p.id_typu == k2.typ_konta);
                        if (k2.stan_konta - tk.prowizja - pr.kwota < 0)
                        {
                            TempData["title"] = "Błąd";
                            TempData["message"] = "Niewystarczający stan konta";
                            TempData["type"] = "error";
                            return RedirectToAction("PanelKlienta", "Home");
                        }
                        else
                        {
                            TempData["title"] = "Sukces";
                            TempData["message"] = "Przelew został wykonany";
                            TempData["type"] = "success";
                        }
                        db.Przelewy_Cykliczne.Add(pr);
                        db.SaveChanges();
                        k.aktywny = false;
                        db.SaveChanges();

                        return RedirectToAction("PanelKlienta", "Home");
                    }


                    return RedirectToAction("PanelKlienta", "Home");
                }
            }
               
        }

        public ActionResult Przelew(Transakcje tr, string password, string kod, string check_code)
        {
            using (MD5 md5Hash = MD5.Create())
            {
                DateTime dt = DateTime.Now;
                if (Session["Klient"] == null)
                {
                    TempData["title"] = "Błąd";
                    TempData["message"] = "Aby uzyskać dostęp do tej strony należy zalogować się do serwisu";
                    TempData["type"] = "error";
                    return RedirectToAction("Login", "Home");
                }
                Klient kl = (Klient)Session["Klient"];

                using (DB_Entities db = new DB_Entities())
                {

                    Kody_Autoryzujace k = db.Kody_Autoryzujace.FirstOrDefault(p => p.kod.Equals(check_code) && p.aktywny == true);
                    if (!check_code.Equals(new RegisterController().GetMd5Hash(md5Hash, kod)) || !kl.haslo.Equals(new RegisterController().GetMd5Hash(md5Hash, password)) || k == null)
                    {

                        TempData["title"] = "Błąd";
                        TempData["message"] = "Podałeś niepoprawne dane";
                        TempData["type"] = "error";

                        return RedirectToAction("PanelKlienta", "Home");
                    }
                    Konta konto = db.Kontas.FirstOrDefault(p => p.numer_konta.Equals(tr.od_kogo));
                    decimal value2 = konto.limit_d ?? 0;
                    if (value2<tr.kwota)
                    {
                        TempData["title"] = "Błąd";
                        TempData["message"] = "Ustawiony limit na rachunku nie pozwala na zrealizowanie przelewu";
                        TempData["type"] = "error";
                        return RedirectToAction("PanelKlienta", "Home");
                    }
                    DateTime d = DateTime.Today;
                    tr.kwota = (Decimal)tr.kwota;
                    if (!ModelState.IsValid)
                    {
                        TempData["title"] = "Błąd";
                        TempData["message"] = "Nieoczekiwany błąd";
                        TempData["type"] = "error";
                        return RedirectToAction("PanelKlienta", "Home");
                    }
                    else
                    {
                        Konta k2 = db.Kontas.FirstOrDefault(p => p.numer_konta.Equals(tr.od_kogo));
                        Typy_Konta tk = db.Typy_Konta.FirstOrDefault(p => p.id_typu == k2.typ_konta);
                        if (k2.stan_konta - tk.prowizja - tr.kwota < 0)
                        {
                            TempData["title"] = "Błąd";
                            TempData["message"] = "Niewystarczający stan konta";
                            TempData["type"] = "error";
                            return RedirectToAction("PanelKlienta", "Home");
                        }
                        tr.wykonane = true;
                        DateTime tmp = (DateTime)tr.data_transakcji;
                        if (DateTime.Compare(dt, tmp) < 0)
                        {
                            TempData["title"] = "Sukces";
                            TempData["message"] = "Przelew zostanie wykonany podanego dnia";
                            TempData["type"] = "success";
                            tr.wykonane = false;
                        }
                        else
                        {
                            TempData["title"] = "Sukces";
                            TempData["message"] = "Przelew został wykonany";
                            TempData["type"] = "success";
                            tr.data_transakcji = dt;
                        }
                        db.Transakcjes.Add(tr);
                        db.SaveChanges();
                        k.aktywny = false;
                        db.SaveChanges();

                        return RedirectToAction("PanelKlienta", "Home");
                    }
                }

            }


        }
        [HttpPost]
        public ActionResult SplataRaty(string password, string kod, string check_code, string rata, string id_kredytu, string konto_cel)
        {
           
            using (MD5 md5Hash = MD5.Create())
            {
                DateTime dt = DateTime.Now;
                if (Session["Klient"] == null)
                {
                    TempData["title"] = "Błąd";
                    TempData["message"] = "Aby uzyskać dostęp do tej strony należy zalogować się do serwisu";
                    TempData["type"] = "error";
                    return RedirectToAction("Login", "Home");
                }
                Klient kl = (Klient)Session["Klient"];


                using (DB_Entities db = new DB_Entities())
                {

                    Kody_Autoryzujace k = db.Kody_Autoryzujace.FirstOrDefault(p => p.kod.Equals(check_code) && p.aktywny == true);
                    if (!check_code.Equals(new RegisterController().GetMd5Hash(md5Hash, kod)) || !kl.haslo.Equals(new RegisterController().GetMd5Hash(md5Hash, password)) || k == null)
                    {

                        TempData["title"] = "Błąd";
                        TempData["message"] = "Podałeś niepoprawne dane";
                        TempData["type"] = "error";

                        return RedirectToAction("PanelKlienta", "Home");
                    }
                     
                    Decimal r = Decimal.Parse(rata);
                    Konta konto = db.Kontas.FirstOrDefault(p => p.id_klienta == kl.id_klienta && p.stan_konta > r);
                   
                    Typy_Konta tk = db.Typy_Konta.FirstOrDefault(p => p.id_typu == konto.typ_konta);
                    
                    if (konto.stan_konta - tk.prowizja - r < 0)
                    {
                        TempData["title"] = "Błąd";
                        TempData["message"] = "Niewystarczający stan konta";
                        TempData["type"] = "error";
                        return RedirectToAction("PanelKlienta", "Home");
                    }
                    Debug.WriteLine(r);
                    Transakcje tr = new Transakcje { dane_osobowe = kl.imie + " " + kl.nazwisko, dane_osobowe_nadawca = "Bank Świnka", data_transakcji = dt, do_kogo = "04175012822459556296178942", kwota = Math.Round(r,2), od_kogo = konto.numer_konta, tytul = "Spłata raty kredytu", wykonane = true, kategoria = 5, typ_transakcji = 2 };
                    k.aktywny = false;
                 
                        db.SaveChanges();

                    try
                    {

WebApplication1/WebApplication1/Views/Home/Glowna.cshtml
@using WebApplication1.Models
@{ List<Acc_Info> info = (List<Acc_Info>)ViewData["info"];  }

<div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
        <div class="container">
            <br><br>
            <h1 class="header center black-text text-lighten-2">Konto oszczędnościowe</h1>
            <div class="row center">
                <h5 class="header col s12 light brown-text">Oprocentowanie konta, jak na lokacie oraz swobodny dostęp do wszystkich środków!</h5>
            </div>
            <div class="row center">
                @Html.ActionLink("Załóż konto", "Registration", "Home", null, new { @style = "color:black;", @id = "download-button", @class = "btn-large waves-effect waves-light teal lighten-1" })
            </div>
            <br><br>

        </div>
    </div>
    <div class="parallax"><img src="~/img/deposit/1.jpg" alt="Unsplashed background img 1"></div>
</div>







<div class="container">
    <div class="section">

        <div class="row">
            <div class="col s12 center">
                <h3><i class="mdi-content-send brown-text"></i></h3>
                <h4>Poznaj niektóre oferty naszego banku</h4>


                <div class="row">
                    <div class="col s12 m4 l4">
                        <div class="card">
                            <div class="card-image waves-effect waves-block waves-light">
                                <img class="activator" src="~/img/deposit/3.jpg">
                            </div>
                            <div class="card-content">
                                <span class="card-title activator grey-text text-darken-4">Konto @info[0].nazwa_typu<i class="material-icons right">more_vert</i></span>
                                <p>@Html.ActionLink("Załóż teraz!", "Registration", "Home", null)</p>
                            </div>
                            <div class="card-reveal">


                                <span class="card-title grey-text text-darken-4">Konto @info[0].nazwa_typu<i class="material-icons right">close</i></span>

                                    <p>@info[0].opis</p>
                                    @Html.ActionLink("Załóż teraz!", "Registration", "Home", null, new { @class = "waves-effect waves-light btn gradient-45deg-deep-purple-blue mt-2 mr-2" })





                            </div>
                        </div>
                    </div>
                    <div class="col s12 m4 l4">
                        <div class="card">
                            <div class="card-image waves-effect waves-block waves-light">
                                <img class="activator" src="~/img/deposit/4.jpg">
                            </div>
                            <div class="card-content">
                                <span class="card-title activator grey-text text-darken-4">Konto @info[1].nazwa_typu<i class="material-icons right">more_vert</i></span>
                                <p>@Html.ActionLink("Załóż teraz!", "Registration", "Home", null)</p>
                            </div>
                            <div class="card-reveal">

                                <span class="card-title grey-text text-darken-4">Konto @info[1].nazwa_typu<i class="material-icons right">close</i></span>

                                <p>@info[1].opis</p>
                                @Html.ActionLink("Załóż teraz!", "Registration", "Home", null, new { @class = "waves-effect waves-light btn gradient-45deg-deep-purple-blue mt-2 mr-2" })


                            </div>
                        </div>
                    </div>

                    <div class="col s12 m4 l4">
                        <div class="card">
                            <div class="card-image waves-effect waves-block waves-light">
                                <img class="activator" src="~/img/deposit/2.jpg">
                            </div>
                            <div class="card-content">
                                <span class="card-title activator grey-text text-darken-4">Konto @info[2].nazwa_typu<i class="material-icons right">more_vert</i></span>
                                <p>@Html.ActionLink("Załóż teraz!", "Registration", "Home", null)</p>
                            </div>
                            <div class="card-reveal">

                                <span class="card-title grey-text text-darken-4">Konto @info[2].nazwa_typu<i class="material-icons right">close</i></span>

                                <p>@info[2].opis</p>
                                @Html.ActionLink("Załóż teraz!", "Registration", "Home", null, new { @class = "waves-effect waves-light btn gradient-45deg-deep-purple-blue mt-2 mr-2" })


                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>


<div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
        <div class="container">
            <div class="row center">
                <h1 class="header center white-text text-lighten-2">Kredyt hipoteczny?</h1>
                <h5 class="header col s12 light white-text"> <b> Z naszym bankiem złożenie wniosku zajmie Ci to 5 minut!</b></h5>
            </div>
        </div>
    </div>
    <div class="parallax"><img src="~/img/deposit/5.jpg" alt="Unsplashed background img 3"></div>
</div>

WebApplication1/WebApplication1/Views/Home/Login.cshtml
@model WebApplication1.Klienci

@{
    ViewBag.Title = "Login";
}
@if (Session["Klient"] != null)
{
    Response.Redirect("PanelKlienta");
}



    <!-- END HEADER -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- START MAIN -->
    <div class="container">
        <center>
            <div class="z-depth-3 y-depth-3 x-depth-3 grey  lighten-4 row" style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px; margin-top: 100px; solid #EEE; width:60%;">



                @using (Html.BeginForm("Login", "Home", FormMethod.Post))
                {


                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    if (@ViewBag.Message != null)
                    {
                        <div style="border: 1px solid red">
                            @ViewBag.Message
                        </div>
                    }
                    if (Session["UserID"] == null)
                    {
                        <div class="card-content">
                            <h4 class="card-title">Logowanie</h4>

                            <div class="row">
                                <div class="input-field col s12">
                                    @Html.LabelFor(a => a.login, "Login")
                                    @Html.TextBoxFor(a => a.login)
                                    @Html.ValidationMessageFor(a => a.login)

                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    @Html.LabelFor(a => a.haslo, "Hasło")
                                    @Html.PasswordFor(a => a.haslo, new { required = "required" })
                                    @Html.ValidationMessageFor(a => a.haslo)


                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="input-field col s12 white-text">

                                <button class="waves-effect waves-light gradient-45d    eg-deep-purple-blue btn btn-block z-depth-4" type="submit" style="color:white;">Login</button>

                            </div>
                        </div>
                        @Html.ActionLink("Zapomniałem hasła", "Reset", "Register", null, new { @style = "color:blue;" })
                    }

                }


            </div>
        </center>
    </div>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br />
    <br />

WebApplication1/WebApplication1/Views/Home/PanelKredytow.cshtml
@model WebApplication1.Models.Kod
@using WebApplication1.Models
@{ List<infoKredyt> list = (List<infoKredyt>)TempData["l_w_kredytow"];}
@{ List<subKonta> r_list = (List<subKonta>)Session["konta"];}


<div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
        <div class="container">
            <div class="row center">
                <h1 class="header center white-text text-lighten-2">Kredyt hipoteczny?</h1>
                <h5 class="header col s12 light white-text"> <b> Z naszym bankiem złożenie wniosku zajmie Ci to 5 minut!</b></h5>
            </div>
        </div>
    </div>
    <div class="parallax"><img src="~/img/deposit/5.jpg" alt="Unsplashed background img 3"></div>
</div>


<div class="container">
    <div class="section">

        @if (list.Count != 0)
        {
            int i = 0;
            foreach (var item in list)
            {
                string m = item.kwota.ToString();
                m = m.Substring(0, m.Length - 2);
                var data_zaw = @item.data.GetValueOrDefault().ToString("dd/MM/yyyy");
                <ul class="collapsible">
                    <li>
                        @if (item.raty_pozostale == 0)
                        {
                            <div class="collapsible-header"><h6 class="truncate">Kredyt na kwotę @m złotych, zawiązany @data_zaw - SPŁACONY </h6></div>
                        }
                        else
                        {
                            <div class="collapsible-header"><h6 class="truncate">Kredyt na kwotę @m złotych, zawiązany @data_zaw - AKTYWNY </h6></div>
                        }
                        <div class="collapsible-body">
                            <p>Podstawowe dane dotyczące tego kredytu:</p>
                            <table>
                                @if (item.raty_pozostale == 0)
                                {
                                    <tr>
                                        <th style="width:30%">Status:</th>
                                        <td>Spłacony</td>
                                    </tr>
                                }
                                else
                                {
                                    <tr>
                                        <th style="width:30%">Status:</th>
                                        <td>Aktywny</td>
                                    </tr>
                                }
                                <tr>
                                    <th>Kwota kredytu:</th>
                                    <td>@m złotych</td>
                                </tr>
                                <tr>
                                    <th>Wysokość prowizji:</th>
                                    <td>@item.prowizja %</td>
                                </tr>
                                <tr>
                                    <th>Wysokość oprocentowania:</th>
                                    <td>@item.oprocentowanie %</td>
                                </tr>
                                <tr>
                                    <th>Data wzięcia pożyczki:</th>
                                    <td>@data_zaw</td>
                                </tr>
                                <tr>
                                    <th>Ilość rat:</th>
                                    @if (item.okres == 1)
                                    {
                                        <td>@item.okres rata</td>

                                    }
                                    @if (item.okres < 5 && item.okres > 1)
                                    {
                                        <td>@item.okres raty</td>

                                    }
                                    @if (item.okres > 5)
                                    {
                                        <td>@item.okres rat</td>

                                    }
                                </tr>
                                <tr>
                                    <th>Wysokość RRSO:</th>
                                    <td>@item.rrso %</td>
                                </tr>
                                @if (item.raty_pozostale > 0)
                                {
                                    var termin = @item.termin_splaty.GetValueOrDefault().ToString("dd/MM/yyyy");
                                    string kwota_raty = item.kwota_najbliszej_raty.ToString();
                                    kwota_raty = kwota_raty.Substring(0, kwota_raty.Length - 2);
                                    <tr>
                                        <th>Wysokość najbliższej raty: </th>
                                        <td>@kwota_raty złotych</td>
                                    </tr>
                                    <tr>
                                        <th>Termin spłaty najbliższej raty:</th>
                                        <td>@termin</td>
                                    </tr>
                                    <tr>
                                        <th>Ilość pozostałych rat:</th>
                                        @if (item.raty_pozostale == 1)
                                        {
                                            <td>@item.raty_pozostale rata</td>

                                        }
                                        @if (item.raty_pozostale < 5 && item.raty_pozostale > 1)
                                        {
                                            <td>@item.raty_pozostale raty</td>

                                        }
                                        @if (item.raty_pozostale > 5)
                                        {
                                            <td>@item.raty_pozostale rat</td>

                                        }
                                    </tr>
                                    <tr>
                                        
                                        <td colspan="2">
                                            <center> <a class="waves-effect waves-light btn modal-trigger" href="#modal@(item.id_kr)">Jeśli chcesz spłacić najbliższą ratę, kliknij tutaj</a> </center>
                                        </td>
                                    </tr>
                                    <div id="modal@(item.id_kr)" class="modal">
                                        <div class="modal-content">
                                            <h4>Autoryzacja</h4>
                                            <div class="row">
                                                @using (Html.BeginForm("SplataRaty", "Create", FormMethod.Post))
                                                {

                                                    <div class="input-field col s6">
                                                        Podaj hasło: <input type="password" class="validate" name="password" maxlength="50" minlength="6" required />
                                                    </div>

                                                    <div class="input-field col s6">
                                                        Podaj kod autoryzacyjny numer @Html.DisplayFor(p => p.numer_kodu):<input type="text" class="validate" name="kod" maxlength="6" minlength="6" required />
                                                        @Html.Hidden("check_code", @Html.DisplayFor(p => p.kod))
                                                    </div>
                                                    <div class="input-field col s6">
                                                        Kwota do zapłaty: @kwota_raty złotych
                                                    </div>
                                                    <input type="hidden" name="id_kredytu" value=" @item.id_kr" />
                                                    <input type="hidden" name="rata" value=" @item.kwota_najbliszej_raty" />

                                                    <label for="konto_cel">Wybierz konto docelowe: </label>
                                                    <select name="konto_cel" id="konto_cel">

                                                        @foreach (var item2 in r_list)
                                                        {
                                                            string c1 = @item2.numer_konta.Substring(0, 2);
                                                            string c2 = @item2.numer_konta.Substring(2);
                                                            c2 = System.Text.RegularExpressions.Regex.Replace(c2, ".{4}", "$0 ");
                                                            string x = item2.stan_konta.ToString();
                                                            x = x.Substring(0, m.Length - 2);
                                                            <option value="@item2.numer_konta"> Konto @c1 @c2 (@m zł)</option>
                                                        }
                                                    </select>


                                                    <center>Uwaga! Do przelewu należy doliczyć koszta prowizji!</center>

                                                    <div class="input-field col s12">
                                                        <br />
                                                        <center>
                                                            <input type="submit" value="Spłać ratę" class="btn" />
                                                        </center>
                                                    </div>

                                                }
                                            </div>
                                        </div>
                                    </div>
                                }
                            </table>
                            <br />
                            <br />


                        </div>
                    </li>
                </ul>


            }
        }
        else
        {
            <center>BRAK KREDYTÓW</center>
        }

    </div>
</div>

WebApplication1/WebApplication1/Views/Home/TwojeRachunki.cshtml
@using WebApplication1.Models
@{ List<subKonta> list = (List<subKonta>)TempData["konta"]; int[] cl = (int[])TempData["ile"];}



<div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
        <div class="container">
            <div class="row center">
                <h1 class="header center white-text text-lighten-2">Kredyt hipoteczny?</h1>
                <h5 class="header col s12 light white-text"> <b> Z naszym bankiem złożenie wniosku zajmie Ci to 5 minut!</b></h5>
            </div>
        </div>
    </div>
    <div class="parallax"><img src="~/img/deposit/5.jpg" alt="Unsplashed background img 3"></div>
</div>


<div class="container">
    <div class="section">
        
            @if (list.Count != 0)
            {
                int i = 0;
                foreach (var item in list)
                {

                    string c1 = item.numer_konta.Substring(0, 2);
                    string c2 = item.numer_konta.Substring(2);
                    c2 = System.Text.RegularExpressions.Regex.Replace(c2, ".{4}", "$0 ");
                    string kw = item.stan_konta.ToString().Substring(0, item.stan_konta.ToString().Length - 2);
                        <ul class="collapsible">
                            <li>
                                <div class="collapsible-header"><h6 class="truncate">Konto @item.nazwa_typu: @c1  @c2</h6></div>
                                <div class="collapsible-body">
                                    <p>Podstawowe dane dotyczące tego konta:</p>
                                    <table>
                                        <tr>
                                            <th style="width:30%">Aktualny stan konta:</th>
                                            <td>@kw zł;</td>
                                        </tr>
                                        <tr>
                                            <th>Liczba transakcji z użyciem tego konta:</th>
                                            <td>@cl[i]</td>
                                        </tr>
                                    </table>
                                        <br />  
                                        <br />
                                        @using (Html.BeginForm("UsunKonto", "Delete", FormMethod.Post))
                                        {
                                            <input type="hidden" name="id_konta" value="@item.id_konta" />
                                            <center>
                                                <input type="submit" value="Jeśli chcesz zlikwidować ten rachunek, kliknij tutaj" class="btn" />
                                            </center>
                                        }
                                  
                                </div>
                            </li>
                        </ul>
                  
                    i++;
                }
            }
      
    </div>
</div>